---
content:
  image: quay.io/deconst/content-service
  environment:
    RACKSPACE_USERNAME:
    RACKSPACE_APIKEY:
    RACKSPACE_REGION: DFW
    CONTENT_CONTAINER: deconst-presenter-dev-content
    ASSET_CONTAINER: deconst-presenter-dev-assets
    CONTENT_LOG_LEVEL: DEBUG
  ports:
  - "9000:8080"
mapping:
  image: quay.io/deconst/mapping-service
  environment:
    CONTROL_REPO_URL: https://github.com/deconst/map-example.git
    MAP_LOG_LEVEL: DEBUG
  ports:
  - "9001:8080"
presenter:
  image: quay.io/deconst/presenter
  links:
  - content
  - mapping
  environment:
    CONTENT_SERVICE_URL: http://content:8080/
    MAPPING_SERVICE_URL: http://mapping:8080/
    PRESENTED_URL_DOMAIN: mysite.com
    PRESENTER_LOG_LEVEL: DEBUG
  ports:
  - "80:8080"
